---
title: "&nbsp;" 
output:
  html_document:
    self_contained: yes
---

```{=html}
<style>
element.style {
  width:         1000px;
  height:        600px;
  margin-top:    0px;
  margin-bottom: 25px;
}
</style>
```

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      eval = TRUE, 
                      warning = FALSE, 
                      comment = NA, 
                      cache = FALSE)
```

```{r}
pacman::p_load(tidyverse)
pacman::p_load(crosstalk, plotly)
```

```{r}
birth_data <- readRDS('dat/birth_data.rds')
birth_data_hi <- SharedData$new(birth_data %>% ungroup())
```

```{r}
filter_select(id = "id", 
              label = "Select a site", 
              sharedData = birth_data_hi, 
              group = ~SITENAME,
              multiple = FALSE)
```

```{r}
gg <- ggplot(birth_data_hi) + 
   geom_line(aes(DATE_FLOOR, cumsum, group = SITENAME, color = name)) +
   facet_wrap(~ origin) + 
   scale_colour_manual(values = c('#b2df8a','#fb9a99','#fdbf6f'),
                       guide = "none") +
   labs(x = NULL,
        y = 'Cumulative Data',
        color = NULL) +
   theme_bw(base_size = 12)+
   theme(panel.grid.minor = element_blank(),
         axis.ticks.y.right = element_blank(),
         legend.position = "bottom")

ggplotly(gg, 
         dynamicTicks = TRUE,
         width = 800,
         height = 400,
         tooltip = c("colour","x","y")) %>% 
   hide_legend() %>% 
   config(displayModeBar = F)
```
