---
title: "&nbsp;" 
output:
  html_document:
    self_contained: yes
---

```{=html}
<style>
element.style {
  width:         1200px;
  height:        900px;
  margin-top:    25px;
  margin-bottom: 25px;
}
</style>
```

```{r include = FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      eval = TRUE, 
                      warning = FALSE, 
                      comment = NA, 
                      cache = FALSE)
```

```{r}
pacman::p_load(tidyverse)
pacman::p_load(trelliscopejs)
pacman::p_load(plotly)
```

```{r}
birth_data <- readRDS('dat/birth_data.rds')
```

```{r}
#| panel: fill
gg <- birth_data %>%
   ungroup() %>% 
   group_nest(SITENAME) %>% 
   rowwise() %>% 
   mutate(babies =  max(data %>% filter(name == 'B-Consented') %>% pull(cumsum) ),
          mothers = max(data %>% filter(name == 'M-Consented') %>% pull(cumsum) ),
          gg = list( ggplot(data) + 
                        geom_line(aes(DATE_FLOOR, cumsum, color = name)) +
                        facet_wrap(~ origin) +
                        scale_colour_manual(values = c('#b2df8a','#fb9a99','#fdbf6f'),
                                            guide = "none") +
                        labs(x = NULL,
                             y = 'Cumulative Data',
                             color = NULL) +
                        theme_bw(base_size = 12)+
                        theme(panel.grid.minor = element_blank(),
                              axis.ticks.y.right = element_blank(),
                              legend.position = "bottom")),
          plotly = list( ggplotly(gg, 
                                  dynamicTicks = TRUE,
                                  width = 800,
                                  height = 400,
                                  tooltip = c("colour","x","y")) %>% 
                            hide_legend() %>% 
                            config(displayModeBar = F) ))

gg %>%
   ungroup() %>% 
   trelliscope(name = 'Site Enrollement',
               desc = 'Visualization w/ trelliscope',
               panel_col = 'plotly',
               path = './trelliscope',
               ncol = 1,
               nrow = 1,
               height = 900,
               width  = 600,
               state = list(sort = list(sort_spec('SITENAME'))))
```
